version: '3.8'

services:
  db:
    ports:
      - "5432:5432"
    container_name: library-postgres
    image: postgres:16
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    networks:
      - default
    restart: on-failure

  backend:
    build: .
    container_name: library-backend
    ports:
      - "8080:8080"
    environment:
      db-url: jdbc:postgresql://db:5432/library
      db-username: postgres
      db-password: 1234
    depends_on:
      - db
    networks:
      - default

volumes:
  db_data: